<?php

namespace DoctrineProxies\__CG__\AdminFox\Entities;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class E_Company extends \AdminFox\Entities\E_Company implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array<string, null> properties to be lazy loaded, indexed by property name
     */
    public static $lazyPropertiesNames = array (
);

    /**
     * @var array<string, mixed> default values of properties to be lazy loaded, with keys being the property names
     *
     * @see \Doctrine\Common\Proxy\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array (
);



    public function __construct(?\Closure $initializer = null, ?\Closure $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', 'id', 'name', 'active', 'phone', 'email', 'externalID', 'internalID', 'clientID', 'address1', 'address2', 'postalCode', 'city', 'codeNAF', 'country', 'usefulData', 'SIRET', 'companyType', 'status', 'globalDiscount', 'outstandingAllowedAmount', 'outstandingCurrentAmount', 'intraCommunityVAT', 'VATRate', 'franchiseName', 'origin', 'parentCompany', 'sites', 'nullableProperties'];
        }

        return ['__isInitialized__', 'id', 'name', 'active', 'phone', 'email', 'externalID', 'internalID', 'clientID', 'address1', 'address2', 'postalCode', 'city', 'codeNAF', 'country', 'usefulData', 'SIRET', 'companyType', 'status', 'globalDiscount', 'outstandingAllowedAmount', 'outstandingCurrentAmount', 'intraCommunityVAT', 'VATRate', 'franchiseName', 'origin', 'parentCompany', 'sites', 'nullableProperties'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (E_Company $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy::$lazyPropertiesDefaults as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @deprecated no longer in use - generated code now relies on internal components rather than generated public API
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId(): ?int
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function getName(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getName', []);

        return parent::getName();
    }

    /**
     * {@inheritDoc}
     */
    public function isActive(): bool
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'isActive', []);

        return parent::isActive();
    }

    /**
     * {@inheritDoc}
     */
    public function getPhone(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPhone', []);

        return parent::getPhone();
    }

    /**
     * {@inheritDoc}
     */
    public function getExternalID(): ?int
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getExternalID', []);

        return parent::getExternalID();
    }

    /**
     * {@inheritDoc}
     */
    public function getAddress1(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAddress1', []);

        return parent::getAddress1();
    }

    /**
     * {@inheritDoc}
     */
    public function getAddress2(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAddress2', []);

        return parent::getAddress2();
    }

    /**
     * {@inheritDoc}
     */
    public function getPostalCode(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPostalCode', []);

        return parent::getPostalCode();
    }

    /**
     * {@inheritDoc}
     */
    public function getCity(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCity', []);

        return parent::getCity();
    }

    /**
     * {@inheritDoc}
     */
    public function getCodeNAF(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCodeNAF', []);

        return parent::getCodeNAF();
    }

    /**
     * {@inheritDoc}
     */
    public function getUsefulData(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUsefulData', []);

        return parent::getUsefulData();
    }

    /**
     * {@inheritDoc}
     */
    public function getSIRET(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSIRET', []);

        return parent::getSIRET();
    }

    /**
     * {@inheritDoc}
     */
    public function getSites()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSites', []);

        return parent::getSites();
    }

    /**
     * {@inheritDoc}
     */
    public function getCompanyType(): ?int
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCompanyType', []);

        return parent::getCompanyType();
    }

    /**
     * {@inheritDoc}
     */
    public function getStatus(): ?int
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getStatus', []);

        return parent::getStatus();
    }

    /**
     * {@inheritDoc}
     */
    public function getGlobalDiscount(): ?int
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getGlobalDiscount', []);

        return parent::getGlobalDiscount();
    }

    /**
     * {@inheritDoc}
     */
    public function getOutstandingAllowedAmount(): ?float
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getOutstandingAllowedAmount', []);

        return parent::getOutstandingAllowedAmount();
    }

    /**
     * {@inheritDoc}
     */
    public function getOutstandingCurrentAmount(): ?float
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getOutstandingCurrentAmount', []);

        return parent::getOutstandingCurrentAmount();
    }

    /**
     * {@inheritDoc}
     */
    public function getInternalID(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getInternalID', []);

        return parent::getInternalID();
    }

    /**
     * {@inheritDoc}
     */
    public function getClientID(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getClientID', []);

        return parent::getClientID();
    }

    /**
     * {@inheritDoc}
     */
    public function getCountry(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCountry', []);

        return parent::getCountry();
    }

    /**
     * {@inheritDoc}
     */
    public function getParentCompany()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getParentCompany', []);

        return parent::getParentCompany();
    }

    /**
     * {@inheritDoc}
     */
    public function getFranchiseName(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFranchiseName', []);

        return parent::getFranchiseName();
    }

    /**
     * {@inheritDoc}
     */
    public function getOrigin(): ?int
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getOrigin', []);

        return parent::getOrigin();
    }

    /**
     * {@inheritDoc}
     */
    public function getIntraCommunityVAT()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIntraCommunityVAT', []);

        return parent::getIntraCommunityVAT();
    }

    /**
     * {@inheritDoc}
     */
    public function getVATRate()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getVATRate', []);

        return parent::getVATRate();
    }

    /**
     * {@inheritDoc}
     */
    public function getEmail()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEmail', []);

        return parent::getEmail();
    }

    /**
     * {@inheritDoc}
     */
    public function update($params)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'update', [$params]);

        return parent::update($params);
    }

    /**
     * {@inheritDoc}
     */
    public function getProperties()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getProperties', []);

        return parent::getProperties();
    }

    /**
     * {@inheritDoc}
     */
    public function updateNullablePropertiesArray()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'updateNullablePropertiesArray', []);

        return parent::updateNullablePropertiesArray();
    }

    /**
     * {@inheritDoc}
     */
    public function getProperty($propName, $asArray = false)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getProperty', [$propName, $asArray]);

        return parent::getProperty($propName, $asArray);
    }

    /**
     * {@inheritDoc}
     */
    public function setDateProperty($propName, $dateString)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDateProperty', [$propName, $dateString]);

        return parent::setDateProperty($propName, $dateString);
    }

    /**
     * {@inheritDoc}
     */
    public function __toString()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, '__toString', []);

        return parent::__toString();
    }

    /**
     * {@inheritDoc}
     */
    public function generateTargetEntityString()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'generateTargetEntityString', []);

        return parent::generateTargetEntityString();
    }

    /**
     * {@inheritDoc}
     */
    public function getMandatoryProperties(): array
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMandatoryProperties', []);

        return parent::getMandatoryProperties();
    }

    /**
     * {@inheritDoc}
     */
    public function checkForMissingFields(): bool
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'checkForMissingFields', []);

        return parent::checkForMissingFields();
    }

}
