<?php

namespace DoctrineProxies\__CG__\AdminFox\Entities;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class E_Activity extends \AdminFox\Entities\E_Activity implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array<string, null> properties to be lazy loaded, indexed by property name
     */
    public static $lazyPropertiesNames = array (
);

    /**
     * @var array<string, mixed> default values of properties to be lazy loaded, with keys being the property names
     *
     * @see \Doctrine\Common\Proxy\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array (
);



    public function __construct(?\Closure $initializer = null, ?\Closure $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', 'id', 'title', 'content', 'creationDate', 'lastUpdate', 'sendingDate', 'activityType', 'recipientReference', 'deadline', 'realDeadline', 'estimatedDuration', 'realDuration', 'tags', 'mailTo', 'mailCC', 'mailCCI', 'status', 'authorUser', 'authorCompany', 'authorContact', 'authorPerson', 'recipientUser', 'recipientCompany', 'recipientContact', 'recipientPerson', 'linkedBusiness', 'nullableProperties'];
        }

        return ['__isInitialized__', 'id', 'title', 'content', 'creationDate', 'lastUpdate', 'sendingDate', 'activityType', 'recipientReference', 'deadline', 'realDeadline', 'estimatedDuration', 'realDuration', 'tags', 'mailTo', 'mailCC', 'mailCCI', 'status', 'authorUser', 'authorCompany', 'authorContact', 'authorPerson', 'recipientUser', 'recipientCompany', 'recipientContact', 'recipientPerson', 'linkedBusiness', 'nullableProperties'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (E_Activity $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy::$lazyPropertiesDefaults as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @deprecated no longer in use - generated code now relies on internal components rather than generated public API
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId(): ?int
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function getTitle(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTitle', []);

        return parent::getTitle();
    }

    /**
     * {@inheritDoc}
     */
    public function getContent(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getContent', []);

        return parent::getContent();
    }

    /**
     * {@inheritDoc}
     */
    public function getCreationDate(): \DateTime
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCreationDate', []);

        return parent::getCreationDate();
    }

    /**
     * {@inheritDoc}
     */
    public function getLastUpdate(): \DateTime
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLastUpdate', []);

        return parent::getLastUpdate();
    }

    /**
     * {@inheritDoc}
     */
    public function getSendingDate(): ?\DateTime
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSendingDate', []);

        return parent::getSendingDate();
    }

    /**
     * {@inheritDoc}
     */
    public function getActivityType(): int
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getActivityType', []);

        return parent::getActivityType();
    }

    /**
     * {@inheritDoc}
     */
    public function getRecipientReference(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRecipientReference', []);

        return parent::getRecipientReference();
    }

    /**
     * {@inheritDoc}
     */
    public function getAuthorUser(): ?\RFCore\Entities\E_User
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAuthorUser', []);

        return parent::getAuthorUser();
    }

    /**
     * {@inheritDoc}
     */
    public function getAuthorCompany(): ?\AdminFox\Entities\E_Company
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAuthorCompany', []);

        return parent::getAuthorCompany();
    }

    /**
     * {@inheritDoc}
     */
    public function getAuthorContact(): ?\AdminFox\Entities\E_Contact
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAuthorContact', []);

        return parent::getAuthorContact();
    }

    /**
     * {@inheritDoc}
     */
    public function getRecipientUser(): ?\RFCore\Entities\E_User
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRecipientUser', []);

        return parent::getRecipientUser();
    }

    /**
     * {@inheritDoc}
     */
    public function getRecipientCompany(): ?\AdminFox\Entities\E_Company
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRecipientCompany', []);

        return parent::getRecipientCompany();
    }

    /**
     * {@inheritDoc}
     */
    public function getRecipientContact(): ?\AdminFox\Entities\E_Contact
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRecipientContact', []);

        return parent::getRecipientContact();
    }

    /**
     * {@inheritDoc}
     */
    public function getAuthorPerson(): ?\AdminFox\Entities\E_NaturalPerson
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAuthorPerson', []);

        return parent::getAuthorPerson();
    }

    /**
     * {@inheritDoc}
     */
    public function getRecipientPerson(): ?\AdminFox\Entities\E_NaturalPerson
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRecipientPerson', []);

        return parent::getRecipientPerson();
    }

    /**
     * {@inheritDoc}
     */
    public function getLinkedBusiness(): ?\BillingFox\Entities\E_Business
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLinkedBusiness', []);

        return parent::getLinkedBusiness();
    }

    /**
     * {@inheritDoc}
     */
    public function getDeadline(): ?\DateTime
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDeadline', []);

        return parent::getDeadline();
    }

    /**
     * {@inheritDoc}
     */
    public function getRealDeadline(): ?\DateTime
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRealDeadline', []);

        return parent::getRealDeadline();
    }

    /**
     * {@inheritDoc}
     */
    public function getEstimatedDuration(): ?int
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEstimatedDuration', []);

        return parent::getEstimatedDuration();
    }

    /**
     * {@inheritDoc}
     */
    public function getRealDuration(): ?int
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRealDuration', []);

        return parent::getRealDuration();
    }

    /**
     * {@inheritDoc}
     */
    public function getTags(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTags', []);

        return parent::getTags();
    }

    /**
     * {@inheritDoc}
     */
    public function getMailTo(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMailTo', []);

        return parent::getMailTo();
    }

    /**
     * {@inheritDoc}
     */
    public function getMailCC(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMailCC', []);

        return parent::getMailCC();
    }

    /**
     * {@inheritDoc}
     */
    public function getMailCCI(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMailCCI', []);

        return parent::getMailCCI();
    }

    /**
     * {@inheritDoc}
     */
    public function getStatus(): ?int
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getStatus', []);

        return parent::getStatus();
    }

    /**
     * {@inheritDoc}
     */
    public function update($params)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'update', [$params]);

        return parent::update($params);
    }

    /**
     * {@inheritDoc}
     */
    public function getProperties()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getProperties', []);

        return parent::getProperties();
    }

    /**
     * {@inheritDoc}
     */
    public function updateNullablePropertiesArray()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'updateNullablePropertiesArray', []);

        return parent::updateNullablePropertiesArray();
    }

    /**
     * {@inheritDoc}
     */
    public function getProperty($propName, $asArray = false)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getProperty', [$propName, $asArray]);

        return parent::getProperty($propName, $asArray);
    }

    /**
     * {@inheritDoc}
     */
    public function setDateProperty($propName, $dateString)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDateProperty', [$propName, $dateString]);

        return parent::setDateProperty($propName, $dateString);
    }

    /**
     * {@inheritDoc}
     */
    public function __toString()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, '__toString', []);

        return parent::__toString();
    }

    /**
     * {@inheritDoc}
     */
    public function generateTargetEntityString()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'generateTargetEntityString', []);

        return parent::generateTargetEntityString();
    }

    /**
     * {@inheritDoc}
     */
    public function getMandatoryProperties(): array
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMandatoryProperties', []);

        return parent::getMandatoryProperties();
    }

    /**
     * {@inheritDoc}
     */
    public function checkForMissingFields(): bool
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'checkForMissingFields', []);

        return parent::checkForMissingFields();
    }

}
