<?php

const SC_STATUS = 'statusCode';

// define mainly status code of RedFox
const SC_SUCCESS = 200;
const SC_INTERNAL_SERVER_ERROR = 500;
const SC_NOT_FOUND = 404;
const SC_FORBIDDEN = 403;
const SC_PRECONDITION_FAILED = 412;
const SC_CONFLICT = 409;
const SC_BAD_REQUEST = 400;
const SC_UNAUTHORIZED = 401;
const SC_NOT_IMPLEMENTED = 501;
const SC_SERVICE_UNAVAILABLE = 503;
const SC_NOT_ACCEPTABLE = 406;
const SC_METHOD_NOT_ALLOWED = 405;
const SC_UNPROCESSABLE_ENTITY = 422;
const SC_NO_CONTENT = 204;
const SC_CREATED = 201;
const SC_ACCEPTED = 202;
const SC_RESET_CONTENT = 205;
const SC_PARTIAL_CONTENT = 206;
const SC_MULTI_STATUS = 207;
const SC_IM_USED = 226;
const SC_CONTINUE = 100;
const SC_SWITCHING_PROTOCOLS = 101;
const SC_PROCESSING = 102;
const SC_NON_AUTHORITATIVE_INFORMATION = 203;
const SC_MULTIPLE_CHOICES = 300;
const SC_MOVED_PERMANENTLY = 301;
const SC_FOUND = 302;
const SC_SEE_OTHER = 303;
const SC_NOT_MODIFIED = 304;
const SC_USE_PROXY = 305;
const SC_TEMPORARY_REDIRECT = 307;

const SC_DOCTRINE = 600;
const SC_DOCTRINE_ENTITY_UPDATE_ERROR = SC_DOCTRINE + 1;
const SC_DOCTRINE_ENTITY_NOT_FOUND = SC_DOCTRINE_ENTITY_UPDATE_ERROR + 1;
const SC_DOCTRINE_ENTITY_PROPERTIE_NOT_FOUND = SC_DOCTRINE_ENTITY_NOT_FOUND + 1;
const SC_DOCTRINE_PB_DURING_PROCESS = SC_DOCTRINE_ENTITY_PROPERTIE_NOT_FOUND + 1;
const SC_DOCTRINE_DUPLICATE_ENTITY = SC_DOCTRINE_PB_DURING_PROCESS + 1;
const SC_DOCTRINE_ENTITY_DELETE_ERROR = SC_DOCTRINE + 1;

// define start Status Code for all RedFox modules
const SC_COMFOX = 800;

const SC_MAILFOX = 900;

const SC_REDFOX_MAX_VALUE = 1000;
